{% set version = "1.8.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bgmm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bgmm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bgmm/bgmm_{{ version }}.tar.gz
  sha256: fa25954c34e02af1fcdd7512d554b6addc7aafef2f256f6914f7967ae947cfe2

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-car
    - r-combinat
    - r-lattice
    - r-mvtnorm
  run:
    - r-base
    - r-car
    - r-combinat
    - r-lattice
    - r-mvtnorm

test:
  commands:
    - $R -e "library('bgmm')"           # [not win]
    - "\"%R%\" -e \"library('bgmm')\""  # [win]

about:
  home: http://bgmm.molgen.mpg.de/
  license: GPL-3.0-only
  summary: 'Two partially supervised mixture modeling methods:  soft-label and belief-based modeling are implemented. For completeness, we equipped the package also with the functionality of unsupervised, semi- and fully supervised mixture modeling.  The package can be applied also to selection of the best-fitting from a
    set of models with different component numbers or constraints on their structures. For detailed introduction see: Przemyslaw Biecek, Ewa Szczurek, Martin Vingron, Jerzy Tiuryn (2012), The R Package bgmm: Mixture Modeling with Uncertain Knowledge, Journal of Statistical Software  <doi:10.18637/jss.v047.i03>.'
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - nick-youngblut
