{% set version = "1.8.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bgmm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bgmm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bgmm/bgmm_{{ version }}.tar.gz
  sha256: 562862b72eadc54b977d74db230b5533d26248c0780f4ec1932840152d6918e5

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-car
    - r-combinat
    - r-lattice
    - r-mvtnorm
  run:
    - r-base
    - r-car
    - r-combinat
    - r-lattice
    - r-mvtnorm

test:
  commands:
    - $R -e "library('bgmm')"           # [not win]
    - "\"%R%\" -e \"library('bgmm')\""  # [win]

about:
  home: http://bgmm.molgen.mpg.de/
  license: GPL-3
  summary: 'Two partially supervised mixture modeling methods:  soft-label and belief-based modeling are implemented. For completeness, we equipped the package also
    with the functionality of unsupervised, semi- and fully supervised mixture modeling.  The package can be applied also to selection of the best-fitting from a
    set of models with different component numbers or constraints on their structures. For detailed introduction see: Przemyslaw Biecek, Ewa Szczurek, Martin Vingron,
    Jerzy Tiuryn (2012), The R Package bgmm: Mixture Modeling with Uncertain Knowledge, Journal of Statistical Software  <doi:10.18637/jss.v047.i03>.'
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - nick-youngblut
