appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: ZIeV0Tnjj3e1KDjkZ0Qxk3T4BBvqGbdc7axjI28j9sM4ZySxQYm2D8kuTCOzyDodAtM1LZWLeK4iNtoOeoXd8Zq/vb0sbAjqc8HtXP+CaruA+MLSK/jOfxj/HuOinMpdPQPLo+kesLqjFei6zZoiDsjPdfEqupydXYh4WiiUcxHpnm7UeewNf1Zoo1zNR5c5qJqwT0rnkEaO5djqhKTTdE1Pj21P8XhRWNbV3HGx6+8+oveFmZK+YlL9IB/8LyZMt6Uoz8VsmyrjPunBekIb51Us7woel8QvDIoxEOXT+Ave1+0af8IpbpHZXH7LK6eaTa48byAjzRIzN+zWn64B8O3j0BZs2rX0Rj7Z8ZcD8W6zhW9z7VxLGu3Q2BjenCMbpRnJj//dDAzdz3d0eiBEEFGLzF1BbAzrN3PQcQPi6Qq1pA7oPS7jLpD/NgadXGCI2QjOzZIXfkQvr46Y4/RcuU19Wr742zwmoI2RwOm5vZ40q+Dl/O1kTRigfyjaUgUcWJaIK8BcJ/56dtVilakVU9lSJii7Hs7414kFuU7fHpjgti3dUlWU+FyO/Bcna3tW/QH0MVl/HIbRBX3dtl3Z+nNmAIliMPGwnBxIYvFFvFcN6KsTgelFKKX+spMbWoQlHzrQ3nRA3l5+uFQP8tAHZxPzPLFkK1crkJqNiP4GaC8=
